### ISSUE TITLE
About use `prin1-to-string' to generate elisp expr string

### ISSUE THREAD

**Issue by tumashu** [SawfishWM/librep#7]
I want to use prin1-to-string to generate a elisp expr string, for example:

```lisp
(prin1-to-string '(`(test ,(concat "aaa" "bbb"))))
```

Result expected is :  

```
"(`(test ,(concat \"aaa\" \"bbb\")))"
```

but, the real result is；

```
"((backquote (test (backquote-unquote (concat \"aaa\" \"bbb\")))))"
```

this is not a valid elisp expression string,  

How to solve the problem? thanks.

**Comment by Nanolx** [comment]
You should send this question to our mailing-list: sawfish[@]lists[.]tuxfamily[.]org -- as it's not actually an issue (sitting in front of a windows machine at work right now, so can't check it).
